const tablesSchema  = {
    company: `CREATE TABLE IF NOT EXISTS company (
        companyID TEXT PRIMARY KEY NOT NULL,
        companyName TEXT,
        companyContact TEXT,
        companyAddress TEXT,
        companyCity TEXT,
        companyState TEXT,
        companyPostalCode TEXT,
        companyCountry TEXT,
        companyConcept TEXT,
        companyPhone TEXT,
        companyTin TEXT,
        companyType TEXT,
        companyPOS TEXT
     );`,
    category: `CREATE TABLE IF NOT EXISTS categories (
        categoryID TEXT PRIMARY KEY NOT NULL,
        categoryName TEXT,
        parentCategoryID TEXT,
    );`,
    customer: `CREATE TABLE IF NOT EXISTS customers (
        customerID TEXT PRIMARY KEY NOT NULL,
        customerName TEXT,
        customerAddress TEXT,
        customerCity TEXT,
        customerPostalCode TEXT,
        customerCountry TEXT,
        customerContact TEXT,
        customerTin TEXT,
        customerType TEXT,
    );`,
    employee: `CREATE TABLE IF NOT EXISTS employees (
        employeeID TEXT PRIMARY KEY NOT NULL,
        employeeLastName TEXT,
        employeeFirstName TEXT,
        employeeBirthDate TEXT,
        employeePhoto TEXT,
        employeeNotes TEXT,
    );`,
    shipper: `CREATE TABLE IF NOT EXISTS shippers (
        shipperID TEXT PRIMARY KEY NOT NULL,
        shipperName TEXT,
        shipperContact TEXT,
    );`,
    supplier: `CREATE TABLE IF NOT EXISTS suppliers (
        supplierID TEXT PRIMARY KEY NOT NULL, 
        supplierName TEXT,
        supplierContactName TEXT,
        supplierAddress TEXT,
        supplierCity TEXT,
        supplierPostalCode TEXT,
        supplierCountry TEXT,
        supplierPhone TEXT,
    );`,
    product: `CREATE TABLE IF NOT EXISTS products (
        ProductID TEXT PRIMARY KEY NOT NULL,    
        productName TEXT,
        productBarcode TEXT,
        supplierID TEXT,
        categoryID TEXT,
        productUnit TEXT,
        productPrice NUMERIC,
        productQuantity NUMERIC,
    );`,
    order: `CREATE TABLE IF NOT EXISTS  (
        orderID TEXT PRIMARY KEY NOT NULL,
        orderCode TEXT,
        customerID TEXT,
        employeeID TEXT,
        orderDate TEXT,
        shipperID TEXT,
        orderStatus TEXT,
        orderSignature TEXT,
        orderExpiration TEXT,
    );`,
    orderDetail: `CREATE TABLE IF NOT EXISTS  (
        orderDetailID TEXT PRIMARY KEY NOT NULL,
        orderID TEXT,
        productID TEXT,
        orderDetailName TEXT,
        orderDetailPrice NUMERIC,
        orderDetailQuantity NUMERIC,
    );`,
    orderCode: `CREATE TABLE IF NOT EXISTS  (
        orderCodeID TEXT PRIMARY KEY NOT NULL,
        orderCodeNumber NUMERIC,
    );`,
};

export {tablesSchema};